import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import icon from "./assets/img/13.png";
import s from "./layout.module.scss";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PayR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${s.bodySite}`}>
        <header className={s.headerSite}>
          <Image src={icon} alt="Pay_R" />
        </header>
        {children}
      </body>
    </html>
  );
}
